input: "/shared/shen/2026/ultimate/jobs/<job_id>/config/nfcore_spatialvi_samplesheet.csv"
outdir: "/shared/shen/2026/ultimate/jobs/<job_id>/runs/nfcore_spatialvi"
genome: "GRCh38"
max_cpus: 16
max_memory: "96.GB"
max_time: "48.h"
