from __future__ import annotations

from pathlib import Path
import shutil
from typing import Any

import numpy as np
import pandas as pd

from ultimate.config import dump_yaml, validate_project_type
from ultimate.constants import MODULE_ORDER
from ultimate.raw_qc import RAW_CONTRACTS
from ultimate.template_resources import find_template_dir


def init_project(project_type: str, output_dir: Path, *, demo_data: bool = False) -> dict[str, Any]:
    project_type = validate_project_type(project_type)
    output_dir = output_dir.resolve()
    config_dir = output_dir / "config"
    sample_dir = output_dir / "samples"
    data_dir = output_dir / "data"
    intake_dir = output_dir / "intake"
    selected = list(MODULE_ORDER) if project_type == "all" else [project_type]

    config_dir.mkdir(parents=True, exist_ok=True)
    sample_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    intake_dir.mkdir(parents=True, exist_ok=True)
    _copy_intake_templates(intake_dir)

    samplesheet = sample_dir / "samples.tsv"
    samples = _demo_samples()
    samples.to_csv(samplesheet, sep="\t", index=False)

    module_config: dict[str, Any] = {}
    for module_name in MODULE_ORDER:
        enabled = module_name in selected
        matrix_path = data_dir / f"{module_name}_matrix.tsv"
        raw_samplesheet = sample_dir / f"raw_{module_name}.tsv"
        _write_raw_samplesheet(raw_samplesheet, module_name)
        module_config[module_name] = {
            "enabled": enabled,
            "analysis_level": "demo_result" if demo_data else "smoke_backend",
            "is_demo": bool(demo_data),
            "samplesheet": "../samples/samples.tsv",
            "input_matrix": f"../data/{module_name}_matrix.tsv",
            "r_entrypoint": f"scripts/R/{module_name}.R",
            "raw": {
                "enabled": True,
                "input_type": RAW_CONTRACTS[module_name].input_types[0],
                "samplesheet": f"../samples/raw_{module_name}.tsv",
                "output_matrix": f"../data/raw_outputs/{module_name}_standard_matrix.tsv",
                "output_object": f"../data/raw_outputs/{module_name}_standard_object.json",
                "qc": {"enabled": True},
                "toolchain": list(RAW_CONTRACTS[module_name].open_replacements),
            },
        }
        if module_name == "publicdb":
            module_config[module_name]["cohort"] = "TCGA_demo"
            module_config[module_name]["open_immune_fallback"] = "ssGSEA_signature_score"
        if module_name == "single_gene":
            module_config[module_name]["gene"] = "TP53"
        if demo_data:
            _write_demo_matrix(matrix_path, module_name)

    config = {
        "project": {
            "name": output_dir.name,
            "organism": "human",
            "output_dir": f"../runs/{output_dir.name}",
            "server_root": "/shared/shen/2026/ultimate",
            "run_mode": "interactive",
            "job_id": output_dir.name,
            "is_demo": bool(demo_data),
        },
        "analysis_request": "../config/analysis_request.yaml",
        "samples": {
            "samplesheet": "../samples/samples.tsv",
        },
        "design": {
            "condition_column": "condition",
            "control": "control",
            "case": "treated",
            "batch_column": "batch",
            "comparisons": ["treated_vs_control"],
        },
        "resources": {
            "human": {
                "genome": "GRCh38",
                "gtf": "/shared/shen/resources/genomes/human/GRCh38.gtf",
                "orgdb": "org.Hs.eg.db",
            },
            "mouse": {
                "genome": "GRCm39",
                "gtf": "/shared/shen/resources/genomes/mouse/GRCm39.gtf",
                "orgdb": "org.Mm.eg.db",
            },
            "msigdb": "/shared/shen/resources/msigdb",
            "cellchatdb": "/shared/shen/resources/cellchatdb",
            "public_cache": "/shared/shen/2026/ultimate/cache/publicdb",
        },
        "modules": module_config,
        "report": {
            "title": "Ultimate 多组学生信分析报告",
            "language": "zh-CN",
            "style": "soft_color",
            "layout": "clinical_report",
            "figure_format": "png",
            "dpi": 180,
            "notes": "Demo project generated by ultimate init-project.",
        },
    }
    _write_analysis_request(config_dir / "analysis_request.yaml", project_type, selected)
    config_path = dump_yaml(config, config_dir / "project.yaml")
    readme_path = output_dir / "README.md"
    readme_path.write_text(_project_readme(project_type, selected, config_path), encoding="utf-8")
    return {
        "project_type": project_type,
        "output_dir": str(output_dir),
        "config_path": str(config_path),
        "samplesheet": str(samplesheet),
        "modules": selected,
        "demo_data": demo_data,
    }


def _demo_samples() -> pd.DataFrame:
    frame = pd.DataFrame(
        [
            {"sample_id": "CTRL_1", "condition": "control", "batch": "B1", "donor": "D1"},
            {"sample_id": "CTRL_2", "condition": "control", "batch": "B1", "donor": "D2"},
            {"sample_id": "TRT_1", "condition": "treated", "batch": "B2", "donor": "D3"},
            {"sample_id": "TRT_2", "condition": "treated", "batch": "B2", "donor": "D4"},
        ]
    )
    frame["cohort_id"] = "TCGA_demo"
    return frame


def _copy_intake_templates(intake_dir: Path) -> None:
    template_dir = find_template_dir("intake")
    if template_dir is None:
        return
    for path in template_dir.iterdir():
        if path.is_file():
            shutil.copy2(path, intake_dir / path.name)


def _write_raw_samplesheet(path: Path, module_name: str) -> None:
    contract = RAW_CONTRACTS[module_name]
    rows: list[dict[str, Any]] = []
    for sample_id, condition in (("CTRL_1", "control"), ("CTRL_2", "control"), ("TRT_1", "treated"), ("TRT_2", "treated")):
        row: dict[str, Any] = {
            "sample_id": sample_id,
            "condition": condition,
            "batch": "B1" if condition == "control" else "B2",
            "raw_input_type": contract.input_types[0],
        }
        for column in contract.required_columns:
            row.setdefault(column, _raw_placeholder(module_name, column, sample_id))
        rows.append(row)
    frame = pd.DataFrame(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, sep="\t", index=False)


def _raw_placeholder(module_name: str, column: str, sample_id: str) -> str:
    if column == "cohort_id":
        return "TCGA_demo"
    if column in {"sample_id", "condition"}:
        return sample_id if column == "sample_id" else "control"
    if column == "fastq_1":
        return f"../raw/{module_name}/{sample_id}_R1.fastq.gz"
    if column == "fastq_2":
        return f"../raw/{module_name}/{sample_id}_R2.fastq.gz"
    if column == "input_path":
        return f"../raw/{module_name}/{sample_id}"
    return f"../raw/{module_name}/{sample_id}_{column}"


def _write_demo_matrix(path: Path, module_name: str) -> None:
    rng = np.random.default_rng(abs(hash(module_name)) % 2**32)
    features = _features_for(module_name)
    values = rng.normal(loc=7.0, scale=1.0, size=(len(features), 4))
    values[:8, 2:] += 1.4
    frame = pd.DataFrame(values, columns=["CTRL_1", "CTRL_2", "TRT_1", "TRT_2"])
    frame.insert(0, "feature_id", features)
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, sep="\t", index=False)


def _write_analysis_request(path: Path, project_type: str, modules: list[str]) -> None:
    payload = {
        "request_id": path.parent.parent.name,
        "project_type": project_type,
        "enabled_modules": modules,
        "analysis_presets": ["standard"],
        "comparisons": ["treated_vs_control"],
        "figure_requirements": ["统一出图风格", "PNG/PDF 可复用"],
        "special_notes": "按用户明确提供的数据路径、样本表和需求直接运行；不做报价前自动评估。",
    }
    dump_yaml(payload, path)


def _features_for(module_name: str) -> list[str]:
    prefix = {
        "rnaseq": "GENE",
        "scrna": "SCGENE",
        "methylation": "cg",
        "proteomics": "PROT",
        "publicdb": "PUBGENE",
        "wgcna": "WGCNA",
        "single_gene": "GENE",
        "perturb_seq": "GUIDE_TARGET",
        "hto_demux": "HTO",
        "genotype_demux": "SNP",
    }.get(module_name, "FEATURE")
    features = [f"{prefix}_{idx:03d}" for idx in range(1, 41)]
    if module_name == "single_gene":
        features[0] = "TP53"
    return features


def _project_readme(project_type: str, modules: list[str], config_path: Path) -> str:
    return "\n".join(
        [
            f"# Ultimate project: {project_type}",
            "",
            "Run:",
            "",
            "```bash",
            f"ultimate preflight --config {config_path}",
            f"ultimate run --config {config_path}",
            "```",
            "",
            "Enabled modules:",
            *[f"- {module}" for module in modules],
            "",
        ]
    )
