name: ultimate-methylation
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - r-base=4.4
  - r-ggplot2
  - r-pheatmap
  - bioconductor-minfi
  - bioconductor-limma
