name: ultimate-core
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - click
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - seaborn
  - pytest
  - snakemake
  - r-base
  - r-essentials
  - bioconductor-limma
