name: ultimate-scatac-r
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4
  - r-seurat
  - r-signac
  - r-archr
  - bioconductor-chromvar
  - bioconductor-genomicranges
  - bioconductor-minfi
